[tool.poetry]
name = "tap-amazon-vendor-central"
version = "0.1.1"
description = "Singer tap for Amazon Vendor Central via the Selling Partner API."
authors = ["Adil Ahmed"]
keywords = [
    "ELT",
    "Amazon-Vendor-Central",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
requests = "^2.25.1"
singer-sdk = "^0.4.4"
python-amazon-sp-api = "1.4.0"
typing-extensions = "4.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^4.0"
ruff = ">=0.15.0,<0.16.0"


[build-system]
requires = ["poetry-core==1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-amazon-vendor-central = 'tap_amazon_vendor_central.tap:TapAmazonVendorCentral.cli'
