[tox]
envlist = ruff,pytest
isolated_build = true

[testenv:ruff]
deps =
    ruff>=0.15.0,<0.16.0
skip_install = true
commands =
    ruff check .

[testenv:pytest]
deps =
    pytest>=6.2.5
commands =
    pytest tap_amazon_vendor_central/tests
